version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=false
      - APP_URL=${APP_URL:-http://localhost:8080}
      - LOG_CHANNEL=stderr
      - DB_CONNECTION=pgsql
      - DB_HOST=aws-0-us-east-2.pooler.supabase.com
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres.mjlzhgujctdbxgmxcszy
      - DB_PASSWORD=${DB_PASSWORD:-pass}
      - DB_URL=postgresql://postgres.mjlzhgujctdbxgmxcszy:${DB_PASSWORD:-pass}@aws-0-us-east-2.pooler.supabase.com:5432/postgres
    restart: unless-stopped
    volumes:
      - app-storage:/var/www/html/storage

volumes:
  app-storage: 